Ref task 6034: add chapters
awesome-academy/ruby_reading_story_01 pull request #11
Opened 2019-01-30 04:27 UTC by ducnam080797

2019-02-01 00:16 UTC, gaacode requested changes

2019-02-01 00:16 UTC, vuongphan139 commented on app/controllers/chapters_controller.rb
> +end
thêm dòng trống

2019-02-01 00:16 UTC, vuongphan139 commented on app/controllers/chapters_controller.rb
> +      flash[:danger] = "Chapter_not_found."
i18n

2019-02-01 07:18 UTC, gaacode requested changes

2019-02-01 07:18 UTC, vuongphan139 commented on app/controllers/chapters_controller.rb
> +    flash[:danger] = "Chapter_not_found."
thêm method `t` và sửa lại key i18n

2019-02-01 07:18 UTC, vuongphan139 commented on app/controllers/chapters_controller.rb
> +    story = Story.find_by(id: params[:story_id])
bỏ ()

2019-02-01 07:18 UTC, vuongphan139 commented on app/views/stories/new.html.erb
> +    <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) %><br/>
bỏ ()

2019-02-01 07:56 UTC, vuongphan139 commented on app/views/stories/show.html.erb
> +                                  data: {confirm: t(".are_you_sure")}, class: "btn btn-danger", role: "button" %>
indent

2019-02-01 07:57 UTC, vuongphan139 commented on app/views/stories/show.html.erb
> +  <div class="col-md-8 bg-secondary p-3" id="form_chapter">
1 dòng thôi

2019-02-01 09:20 UTC, gaacode requested changes

2019-02-01 09:20 UTC, vuongphan139 commented on app/controllers/stories_controller.rb
>    def load_story
```suggestion
  def find_story
```
nên để tên method là find_story

2019-02-01 09:20 UTC, vuongphan139 commented on app/views/chapters/show.html.erb
> +    <p> <%= t "name_chapter" %>: <%= @chapter.name %></p>
```suggestion
    <p><%= t "name_chapter" %>: <%= @chapter.name %></p>
```

2019-02-01 09:20 UTC, vuongphan139 commented on app/views/chapters/_form.html.erb
> +
xoá dòng này

2019-02-01 09:20 UTC, vuongphan139 commented on app/views/chapters/_form.html.erb
> +
xoá dòng này nữa

2019-02-01 21:46 UTC, gaacode requested changes

2019-02-01 21:46 UTC, vuongphan139 commented on app/controllers/chapters_controller.rb
> +    @chapter = Chapter.find_by id: params[:id]
bỏ dòng này nhé ông.

2019-02-01 21:46 UTC, vuongphan139 commented on app/views/chapters/show.html.erb
> +</div>
bỏ file này đi nhé, vì bây giờ chưa dùng đến. 
cái view show này để hiển thị nội dung chương toàn màn hình cho user đọc ông ạ.  
bớt đc 1 file change.

2019-02-02 00:26 UTC, thanhhungchu95 reviewed
Ko fix cmt của Vương à :v

2019-02-02 00:26 UTC, thanhhungchu95 commented on app/controllers/chapters_controller.rb
> +      flash.now[:danger] = t "add_chapter_failure"
Flash xong ko làm gì à ?

2019-02-02 05:01 UTC, merged