Ref task #6054: edit_user
awesome-academy/ruby_reading_story_01 pull request #31
Opened 2019-02-18 13:57 UTC by ducnam080797

2019-02-18 14:55 UTC, gaacode requested changes

2019-02-18 14:55 UTC, vuongphan139 commented on app/controllers/users_controller.rb
> +    @user = User.find params[:id]
xóa dòng này

2019-02-18 14:55 UTC, vuongphan139 commented on app/controllers/users_controller.rb
> +    @user = User.find_by id: params[:id]
xóa dòng này

2019-02-18 14:55 UTC, vuongphan139 commented on app/controllers/users_controller.rb
> +    if @user.update_attributes user_params
đoạn if else này sai sai rồi nhé.

2019-02-18 14:55 UTC, vuongphan139 commented on app/controllers/users_controller.rb
> +    if @user.update_attributes user_params
dùng update thay vì update_attributes

2019-02-18 14:55 UTC, vuongphan139 commented on app/controllers/users_controller.rb
> +
params.require(:user)
          .permit User::SIGNUP_PARAMS

đổi đoạn này thành 1 dòng thôi nhé.

2019-02-18 14:55 UTC, vuongphan139 commented on app/controllers/users_controller.rb
> +
bỏ () trong hàm `correct_user`

2019-02-18 14:55 UTC, vuongphan139 commented on app/models/story.rb
> +
bỏ dòng 34 này đi

2019-02-19 01:43 UTC, gaacode requested changes

2019-02-19 01:43 UTC, vuongphan139 commented on app/controllers/users_controller.rb
> +      flash[:danger] = t "empty_user"
sao update lỗi lại báo là empty user, sửa nốt cái này rồi TO anh Hưng đi nhé :v

2019-02-19 06:05 UTC, merged